### PR TITLE
Replace the set() Jinja2 filter with a new unique() filter

### PR DESCRIPTION
**Pull request by bartfeenstra**
This fixes https://github.com/bartfeenstra/betty/issues/627. It's a bit slower, but works on unhashable types, and keeps the original order and is therefore stable.

### CODE REVIEW

**Comment by unixmiddleware** [comment]
Still get the error:

File "/home/mark/workspace/betty-pr/betty/betty/assets/templates/page/source.html.j2", line 13, in block "page_content"
    {% set facts = sources | map(attribute='citations') | flatten | map(attribute='facts') | flatten | select('resource') | list | set | list %}
TypeError: unhashable type: 'Person'

I've checked that I have the right branch, as shown by the 'list|set'

**Comment by bartfeenstra** [comment]
@unixmiddleware That looks like you're on another branch still. Did you do `git fetch` and then `git checkout unhashable-resources`?

**Comment by unixmiddleware** [comment]
Hi Bart

The evidence is that I didn't do it, but I repeated the steps and it still
picked up the wrong file.
I deleted the directory and re-cloned the repo and now it picks up the
modified files.

This is what I got before re-cloning the repo, the last line of which says
Already on 'unhashable-resources'

(gramps) mark@debian-brix:~/workspace/betty-pr/betty$ git checkout
unhashable-resources
M betty/ancestry.py
M betty/cli.py
M betty/config.py
M betty/dispatch.py
M betty/fs.py
M betty/jinja2.py
M betty/json.py
M betty/locale.py
M betty/lock.py
M betty/media_type.py
M betty/plugin/anonymizer/__init__.py
M betty/plugin/deriver/__init__.py
M betty/plugin/gramps/__init__.py
M betty/plugin/maps/__init__.py
M betty/plugin/nginx/__init__.py
M betty/plugin/nginx/artifact.py
M betty/plugin/nginx/docker.py
M betty/plugin/nginx/serve.py
M betty/plugin/privatizer/__init__.py
M betty/plugin/trees/__init__.py
M betty/plugin/wikipedia/__init__.py
M betty/search.py
M betty/serve.py
M betty/site.py
M betty/subprocess.py
M betty/tests/__init__.py
M betty/tests/assets/locale/test_translations.py
M betty/tests/assets/templates/meta/test_place_html_j2.py
M betty/tests/plugin/deriver/test__init__.py
M betty/tests/plugin/gramps/test__init__.py
M betty/tests/plugin/nginx/test__init__.py
M betty/tests/plugin/nginx/test_serve.py
M betty/tests/plugin/privatizer/test__init__.py
M betty/tests/plugin/wikipedia/test__init__.py
M betty/tests/test_ancestry.py
M betty/tests/test_cli.py
M betty/tests/test_generate.py
M betty/tests/test_importlib.py
M betty/tests/test_jinja2.py
M betty/tests/test_json.py
M betty/tests/test_locale.py
M betty/tests/test_media_type.py
M betty/tests/test_sass.py
M betty/tests/test_search.py
M betty/tests/test_voluptuous.py
M betty/url.py
Already on 'unhashable-resources'

**Comment by bartfeenstra** [comment]
If you're already on the right branch and want to make sure you've got the [latest commits](https://github.com/bartfeenstra/betty/pull/628/commits), run `git pull`.

**Comment by unixmiddleware** [comment]
Thank you

Next time I encounter the issue I'll try the pull

**Comment by unixmiddleware** [comment]
The issue has been resolved, working well .

**Comment by bartfeenstra** [comment]
Thanks for the review!

**Pull request merged**
