### PR TITLE
fixed Leaflet marker path, added a missing "/" 

### PR DESCRIPTION
**Pull request by rainerth**
The leaflet pin marker showing location im maps was not displayed. I added a "/" in a corresponding regex which fixed the issue for me. Don't know, if this is the right way to get a valid path and if it will also work when no root_path: /xx is set in betty.yaml as in my project.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks, @rainerth ! Would you be able to clean the commit history of this PR so it just contains your fix?

**Comment by rainerth** [comment]
Hi @bartfeenstra, thank you so much for your support on mastering git PRs to your great project. The PR 'german-translation' might be OK now (rebase/push -f), hopefully. 

Cleaning the history for th PR 'leaflet-marker-path' with rebase / squash ended up in a mess :) You might instead reject  the PR and I'll try again after you merged the first one. Hope that's OK for you.

**Comment by bartfeenstra** [comment]
Yeah, totally fine if you want to replace your PR with a new one :)

**Comment by bartfeenstra** [comment]
I seem to have accidentally broken the markers even more in https://github.com/bartfeenstra/betty/pull/1148. Having a quick look to see if I can fix it, but just so you know the code in this area may change. Sorry, did not mean to trample over your work!

**Comment by bartfeenstra** [comment]
@rainerth https://github.com/bartfeenstra/betty/pull/1196 fixes the bug I introduced in https://github.com/bartfeenstra/betty/pull/1148, and I tried to replicate a situation with a root path and that seems to work as well.

**Comment by bartfeenstra** [comment]
I'm closing this as this is likely fixed and as no further responses we're received.

@rainerth Feel free to reopen this or create a new issue or PR if the problem does persist :)

**Pull request closed without merging**
