### PR TITLE
Fix a missing library in Betty Desktop for Linux by packaging on a newer Linux version

### LINKED ISSUE #1044: Install failure on Ubuntu 23.10
Installing on a newly created VM has the same issue as trying to install on a standalone system.

# Ubuntu details

```
(website) mark@aorus:~/workspace/website$ cat /etc/os-release
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
```

# Install command
```
mark@aorus:~/workspace$ python3 -m venv $(pwd)/website
mark@aorus:~/workspace$ cd website/
mark@aorus:~/workspace/website$ source bin/activate
(website) mark@aorus:~/workspace/website$ pip install betty
```

# Install Output

```
Collecting betty
  Using cached betty-0.2.7-py2.py3-none-any.whl (177 kB)
Collecting aiohttp~=3.7 (from betty)
  Obtaining dependency information for aiohttp~=3.7 from https://files.pythonhosted.org/packages/69/8d/769a1e9cdce1c9774dd2edc8f4e94c759256246066e5263de917e5b22a0a/aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata
  Using cached aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting babel~=2.9 (from betty)
  Obtaining dependency information for babel~=2.9 from https://files.pythonhosted.org/packages/86/14/5dc2eb02b7cc87b2f95930310a2cc5229198414919a116b564832c747bc1/Babel-2.13.1-py3-none-any.whl.metadata
  Using cached Babel-2.13.1-py3-none-any.whl.metadata (1.6 kB)
Collecting click~=7.1 (from betty)
  Using cached click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting docker~=4.4 (from betty)
  Using cached docker-4.4.4-py2.py3-none-any.whl (147 kB)
Collecting urllib3<2 (from betty)
  Obtaining dependency information for urllib3<2 from https://files.pythonhosted.org/packages/b0/53/aa91e163dcfd1e5b82d8a890ecf13314e3e149c05270cc644581f77f17fd/urllib3-1.26.18-py2.py3-none-any.whl.metadata
  Using cached urllib3-1.26.18-py2.py3-none-any.whl.metadata (48 kB)
Collecting geopy~=2.0 (from betty)
  Obtaining dependency information for geopy~=2.0 from https://files.pythonhosted.org/packages/e5/15/cf2a69ade4b194aa524ac75112d5caac37414b20a3a03e6865dfe0bd1539/geopy-2.4.1-py3-none-any.whl.metadata
  Using cached geopy-2.4.1-py3-none-any.whl.metadata (6.8 kB)
Collecting jinja2~=2.11 (from betty)
  Using cached Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
Collecting jsonschema~=3.2 (from betty)
  Using cached jsonschema-3.2.0-py2.py3-none-any.whl (56 kB)
Collecting libsass~=0.20 (from betty)
  Using cached libsass-0.22.0-cp36-abi3-manylinux_2_5_x86_64.manylinux1_x86_64.whl (9.4 MB)
Collecting markupsafe~=1.1 (from betty)
  Using cached MarkupSafe-1.1.1.tar.gz (19 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting pdf2image~=1.14 (from betty)
  Using cached pdf2image-1.16.3-py3-none-any.whl (11 kB)
Collecting python-resize-image~=1.1 (from betty)
  Using cached python_resize_image-1.1.20-py2.py3-none-any.whl (8.4 kB)
Collecting pyyaml~=5.3 (from betty)
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3/PyYAML.egg-info/PKG-INFO
      writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
      writing top-level names to lib3/PyYAML.egg-info/top_level.txt
      Traceback (most recent call last):
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mark/workspace/website/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
          self.find_sources()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
          mm.run()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
          self.add_defaults()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "/tmp/pip-build-env-w58dccf9/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

```

### PR DESCRIPTION
**Pull request by bartfeenstra**
This fixes https://github.com/bartfeenstra/betty/issues/1044

### CODE REVIEW

**Comment by unixmiddleware** [comment]
The betty gui started but the console/terminal showed an error

`/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
`

Also, when trying to create a new betty project, there were errors reported

`(betty:15273): Gtk-WARNING **: 06:55:50.988: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
(betty:15273): Gtk-WARNING **: 06:55:50.988: Loading IM context type 'wayland' failed
`

Trying to generate my own family tree website produced an empty output/www folder

However, the demo website worked nicely

`compiling catalog /home/mark/workspace/betty/dist/betty/_internal/betty/assets/locale/nl-NL/betty.po to /home/mark/.betty/cache/locale/3f22fbeb511658f42fc60b0b3253b357/betty.mo
compiling catalog /home/mark/workspace/betty/dist/betty/_internal/betty/assets/locale/uk/betty.po to /home/mark/.betty/cache/locale/19891be3b9efa4f05a4a5b3077baf6c7/betty.mo
compiling catalog /home/mark/workspace/betty/dist/betty/_internal/betty/assets/locale/fr-FR/betty.po to /home/mark/.betty/cache/locale/e40626abd76cc0f2482fbd9a4f1d9c67/betty.mo`

**Comment by unixmiddleware** [comment]
On startup

`/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
`

After a few seconds, without doing anything at all

`** (betty:58486): WARNING **: 16:00:25.072: atk-bridge: get_device_events_reply: unknown signature
`

After selecting to load an existing project

`/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_static_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgioremote-volume-monitor.so
(betty:58486): Gtk-WARNING **: 16:01:51.266: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
(betty:58486): Gtk-WARNING **: 16:01:51.266: Loading IM context type "wayland" failed
(betty:58486): Gtk-WARNING **: 16:01:51.271: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
(betty:58486): Gtk-WARNING **: 16:01:51.271: Loading IM context type "wayland" failed
(betty:58486): Gtk-WARNING **: 16:01:51.272: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
(betty:58486): Gtk-WARNING **: 16:01:51.272: Loading IM context type "wayland" failed
(betty:58486): Gtk-WARNING **: 16:01:51.273: /usr/lib/x86_64-linux-gnu/gtk-3.0/3.0.0/immodules/im-wayland.so: undefined symbol: g_string_free_and_steal
(betty:58486): Gtk-WARNING **: 16:01:51.273: Loading IM context type "wayland" failed
`

After selecting an existing project to load

`
QWidget::setLayout: Attempting to set QLayout "" on _LocalesConfigurationWidget "", which already has a layout
QLayout: Cannot add parent widget _LocalesConfigurationWidget/ to its child layout QVBoxLayout/
`

When trying to generate site, with debugging enabled

`unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-25' coro=<_GenerateThread._generate() done, defined at betty/gui/project.py:559> exception=TypeError("Python type 'Exception' is not supported as a Q_ARG() type")>
Traceback (most recent call last):
  File "betty/gui/project.py", line 562, in _generate
  File "betty/load.py", line 21, in load
  File "betty/app/extension/__init__.py", line 298, in _dispatch
  File "betty/asyncio.py", line 15, in gather
  File "asyncio/taskgroups.py", line 134, in __aexit__
  File "asyncio/taskgroups.py", line 110, in __aexit__
asyncio.exceptions.CancelledError
`

During handling of the above exception, another exception occurred:

`
Traceback (most recent call last):
  File "betty/gui/project.py", line 560, in _generate
  File "betty/gui/error.py", line 66, in __exit__
TypeError: Python type 'Exception' is not supported as a Q_ARG() type
`

**Comment by bartfeenstra** [comment]
Thanks for testing! Im out of ideas for now.

Until this is fixed, are you unblocked by installing Betty through pip?

**Comment by bartfeenstra** [comment]
Closing this after https://github.com/bartfeenstra/betty/pull/1157 and due to the complexity of the problem. We'll need to do some more research on how to make these builds work on Linux.

**Pull request closed without merging**
