### PR TITLE
Add French translations

### PR DESCRIPTION
**Pull request by patlx**
fr_FR-LC_MESSAGES renamed fr_FR/LC_MESSAGES

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thanks for contributing these translations!  Would you be able to rename the directory `betty/assets/locale/fr_FR-LC_MESSAGES` to `betty/assets/locale/fr_FR/LC_MESSAGES/`? Otherwise Betty won't be able to find the translation files and render sites in French.

**Comment by patlx** [comment]
This what I've done. Don't you see it?

Le sam. 28 nov. 2020 à 19:00, Bart Feenstra <notifications@github.com> a
écrit :

**Comment by bartfeenstra** [comment]
I can see that you tried that, but somehow the change didn't make it into this PR. If you follow the *Files changed* tab at the top of this PR, you'll see that the two nested directories unfortunately are still one directory with a combined name.

**Comment by bartfeenstra** [comment]
This PR will also need to document the language in `README.md`, along with the existing three translations that are listed there already.

**Comment by bartfeenstra** [comment]
I merged https://github.com/bartfeenstra/betty/pull/619, which means that compiling and committing `*.mo` files manually is no longer necessary. In short, all anyone needs to do to contribute to translations is add or edit `*.po` files.

**Comment by bartfeenstra** [comment]
@patlx Good morning! Do you still feel like working on this?

**Comment by bartfeenstra** [comment]
@patlx If you don't mind, I'll pick this up, finish the remaining bits, and merge it :)

**Comment by patlx** [comment]
Hello,

What can I do for helping you?

Le lun. 28 déc. 2020 à 23:53, Bart Feenstra <notifications@github.com> a
écrit :

**Comment by bartfeenstra** [comment]
The translations were fine, but the PR itself needed a few tweaks as posted back in November. I took your work ([with credit](https://github.com/bartfeenstra/betty/graphs/contributors)), made the necessary changes, and merged the translations in https://github.com/bartfeenstra/betty/pull/694 and https://github.com/bartfeenstra/betty/pull/693. They'll be available in the upcoming 0.2.5 release.

Thank you for contributing, and enjoy the holiday season :)

**Pull request closed without merging**
