### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by rainerth**
This PR will add a de-DE/betty.po file with German translation resources, some minor formatting fixes the other po files to fix poedit error messages. In addition to that I had to replaced one {xxx}% string {xxx}%% in source an translations to avoid poedit formatting errors.

### CODE REVIEW

**Comment by bartfeenstra** [comment]
Thank you!

If you look at the diff, you can see there are a few more changes than the ones you intended to make. That's because Betty has changed since you forked it. If you rebase your PR branch on Betty's `0.3.x` branch and push the results to your PR, we should all be seeing exactly the changes you made.

**Comment by rainerth** [comment]
Done, now you just see one change in code and some changes in .po files. 

I wonder if I should have better based my 2nd PR on your branch (so only one change in one file will be reported) or on my first PR (so 6+1 changed files are reported).

**Comment by bartfeenstra** [comment]
Excellent! All we need is two small additions to places where we list/use all available translations:
- In `./betty/documentation/usage/translation.rst`, German should be added to the available translations.
- In `_Demo.project()` in `./betty/extension/demo/__init__.py`, the German locale should be enabled as well.

**Comment by bartfeenstra** [comment]
So while your diff is clean now, there are some unrelated commits on this branch. This is my workflow, which is fairly easy and gives a clean result. Do this once for your local forked repo:
- `git remote add upstream https://github.com/bartfeenstra/betty.git` so tell your local fork how to talk to the Betty repository

Any time Betty was updated and you want to update your local repo with the changes:
- `git checkout 0.3.x` to go to the main branch in your own fork
- `git reset --hard upstream/0.3.x` to ensure your `0.3.x` is an exact copy of the latest Betty `0.3.x` code

Then when you're working on your PRs and you want to ensure a clean pull request branch:
- `git checkout rainers-pull-request-branch-123`
- `git rebase 0.3.x` to rewrite your pull request history so it looks like your commits were made just now on the most recent version of Betty, even if you forked some time ago and your branches were out of date
- `git push -f`. `-f` forces the push, which is required because `rainers-pull-request-branch-123` still contains the same changes, but due to the rebase the commit hashes have changed.

**Review by bartfeenstra — APPROVED** [review]

**Comment by bartfeenstra** [comment]
Merged! Thank you :)

**Pull request merged**
