### PR TITLE
Fix missing template files for entity list pages

### LINKED ISSUE #2187: Cotton Candy's file list page fails on missing template file
See https://github.com/Illia-M/test-betty-tree/actions/runs/11649767464/job/32437676231#logs

As originally reported by @Illia-M

### PR DESCRIPTION
**Pull request by bartfeenstra**
This fixes https://github.com/bartfeenstra/betty/issues/2187

## Changes
- Provide a fallback entity list page for any entity type
- Add tests to assert that all Cotton Candy entity list page templates function correctly 
- Fix the bug where the file list page errored

### CODE REVIEW

**Comment by bartfeenstra** [comment]
@Illia-M Can you confirm this solves the problem you ran into?

**Comment by Illia-M** [comment]
@bartfeenstra as I see problem with file not found - but as I see file should be inside gramps package...
https://github.com/Illia-M/test-betty-tree/actions/runs/11670539377/job/32494935155#step:6:97

**Comment by bartfeenstra** [comment]
Can you report each individual problem as a new issue? Then it is easier to keep track of, and fix them one by one 😊

**Comment by Illia-M** [comment]
Of course, sorry

**Pull request merged**
